config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#top'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    'users' , to: 'users#index', as: 'users'
  get    'users/filter/:id', to: 'users#index', as: 'user_filter'
  delete 'users/:id' , to: 'users#destroy', as: 'user_delete'
  get    'users/new' , to: 'users#new'
  post   'users/new' , to: 'users#new', as: 'user_new'
  get    'users/:id/edit' , to: 'users#edit', as: 'users_edit'
  post   'users/edit' , to: 'users#edit', as: 'user_edit'
  get    'users/confirm' , to: 'users#confirm'
  post   'users/confirm' , to: 'users#confirm', as: 'user_confirm'
  get    'users/:id/detail' , to: 'users#detail', as: 'user_detail'
  get    'users/search' , to: 'users#search'
  post   'users/search',  to: 'users#search', as: 'user_search'
  get    'users/:id/matching' , to: 'users#matching', as: 'user_matching'
  post   'users/upload' , to: 'users#upload'
  post   'users/:id/download' , to: 'users#download', as: 'user_download'
  get    'projects' , to: 'projects#index', as: 'projects'
  get    'projects/new' , to: 'projects#new'
  post   'projects/new' , to: 'projects#new', as: 'project_new'
  get    'projects/:id/edit' , to: 'projects#edit', as: 'projects_edit'
  post   'projects/edit' , to: 'projects#edit', as: 'project_edit'
  get    'projects/confirm' , to: 'projects#confirm'
  post   'projects/confirm' , to: 'projects#confirm', as: 'project_confirm'
  get    'projects/:id/detail' , to: 'projects#detail', as: 'project_detail'
  get    'projects/search' , to: 'projects#search'
  post   'projects/search',  to: 'projects#search', as: 'project_search'
  get    'projects/:id/matching' , to: 'projects#matching', as: 'project_matching'
  namespace 'api' do
    namespace 'v1' do
      post   'users/search',  to: 'users#search', as: 'user_search'
      get    'users/favorite',  to: 'users#favorite'
      post   'users/favorite',  to: 'users#favorite', as: 'user_favorite'
      post   'projects/search',  to: 'projects#search', as: 'project_search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  enum admin: { general: false, admin: true }
  scope :engineer, -> { where(admin_flag: false) }
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController

      ## JOIN句(定数)
      JOIN_PHASE = ["INNER JOIN possessed_skills ON users.employee_number = possessed_skills.employee_number",
                    "LEFT OUTER JOIN project_members ON users.employee_number = project_members.employee_number",
                    "INNER JOIN project_members ON users.employee_number = project_members.employee_number"]
      ## 参画有無(定数)
      JOIN_OR_NOT = ["無", "有"]

      def search
        ## 検索結果
        result = []
        ## DBからは氏名(like検索)とスキル(IN検索)と参画有無(結合)で絞る
        ## 参画有無
        if params[:joinOrNot]
          ## 参画無
          if params[:joinOrNot] == JOIN_OR_NOT[0]
            joins = JOIN_PHASE[1]
            joinsJouken = "start_date is null AND end_date is null"
          ## 参画有
          elsif params[:joinOrNot] == JOIN_OR_NOT[1]
            joins = JOIN_PHASE[2]
            now = Date.today.strftime("%Y-%m-%d")
            joinsJouken = "(start_date is not null AND end_date is null) OR (#{now} <= end_date)"
          end
        end
        ## スキル
        if params[:skills]
          ## スキル以外に他に入力されている場合(年齢は両方入力か両方未入力)
          if params[:name].present? or (params[:age_from].present? and params[:age_to].present?) or (params[:age_from].empty? and params[:age_to].empty?)
            jouken = ""
            params[:skills].each_with_index do |skill, index|
              jouken = jouken + "skill_id = " + skill
              if index < params[:skills].count - 1
                jouken.concat(" OR ")
              end
            end
          ## スキルのみ入力されている場合
          else
            ## 選択したスキルが1つの場合
            if params[:skills].count == 1
              jouken = "skill_id = ?"
            elsif params[:skills].count >= 2
              jouken = "skill_id IN (?)"
            end
          end
          unless jouken.empty?
            ## 管理者はスキルがないため管理者フラグの判定は不要
            @users = params[:joinOrNot].empty? ?
                      User.joins(JOIN_PHASE[0]).where("name like ?", "%"+params[:name]+"%").where(jouken, params[:skills]).distinct :
                       User.joins(JOIN_PHASE[0]).joins(joins).where("name like ?", "%"+params[:name]+"%").where(jouken, params[:skills]).where(joinsJouken).distinct.order(:employee_number)
          end
        else
          @users = params[:joinOrNot].empty? ?
                    User.where("admin_flag <> true AND name like ?", "%"+params[:name]+"%") :
                     User.joins(joins).where("admin_flag <> true AND name like ?", "%"+params[:name]+"%").where(joinsJouken).distinct.order(:employee_number)
        end
        ## 参画終了日(入力日付の1か月前 ≦ 参画終了日 ≦ 入力日付の1か月後)
        @users = User.joins(JOIN_PHASE[2])
                      .where("users.employee_number in (?) AND end_date BETWEEN ? AND ?",
                        @users.pluck(:employee_number),
                        (Date.parse(params[:joinEndDate]) << 1).strftime("%Y-%m-%d"),
                        (Date.parse(params[:joinEndDate]) >> 1).strftime("%Y-%m-%d")).order(:employee_number) if params[:joinEndDate].present? and @users.pluck(:employee_number).present?
        ## 年齢
        if params[:age_from].present? and params[:age_to].present?
          count = 0
          @users.each do |user|
            age = getAge(user.birthday)
            if params[:age_from].to_i <= age and age <= params[:age_to].to_i
              result[count] = user.employee_number
              count = count + 1
            end
          end
          result = User.where(employee_number: result)
        else
          result = @users
        end
        render json: result.count
      end

      def favorite
        ## Postメソッドのみ実行
        if request.post?
          ## params[:favorite]が文字列で渡されるので、boolean型に変換する
          params[:favorite] = params[:favorite] == "true" ? true : false
          if params[:favorite] ## trueの場合、レコード登録(案件番号、社員番号、ログイン社員番号(基本的に管理者))
            params[:created_employee_number] = current_user.employee_number
            @projectMatching = ProjectMatching.new(project_matching_params)
            @projectMatching.save
          else ## falseの場合、押下した案件番号と社員番号に紐づくレコード削除
            @projectMatching = ProjectMatching.where(project_id: params[:project_id], employee_number: params[:employee_number])
            @projectMatching.delete_all
          end
        else
          ## それ以外(Getメソッド)の場合はエンジニア一覧 or エンジニア詳細画面 or ログイン画面へ遷移
          ## ログイン時のみユーザー情報取得
          user = User.find(current_user.employee_number) if current_user.present?
          flash[:danger] = '不正なリクエストです。'
          redirect_to root_url user
        end
      end

      private

        def project_matching_params
          params.permit(:project_id, :employee_number, :created_employee_number)
        end

        ## 誕生日から実年齢を取得するメソッド
        def getAge(birthday)
          today = Date.today.to_time.strftime('%Y%m%d').to_i
          birth = birthday.to_time.strftime('%Y%m%d').to_i
          return ((today - birth)/10000).to_i
        end

    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  ## 単価を金額表示(3桁区切り)にするメソッド
  def getPriceDisplay(price)
    return price.present? ? price.to_s(:delimited).concat("円") : ""
  end

  ## 年プルダウンを取得するためのMap
  def getYearMap
    hash = {}
    ## 1950年～現在年まで取得
    for year in 1950..Date.today.year.to_i
      hash[year] = year
    end
    return hash
  end

  ## 経験年プルダウンを取得するためのMap
  def getExpYearMap
    hash = {}
    ## 30年まで取得
    for year in 0..30
      hash[year] = year
    end
    return hash
  end

  ## 月プルダウンを取得するためのMap
  def getMonthMap
    hash = {}
    ## 1月～12月まで取得
    for month in 1..12
      hash[month] = month
    end
    return hash
  end

  ## 経験月プルダウンを取得するためのMap
  def getExpMonthMap
    hash = {}
    ## 0ヶ月～11ヶ月まで取得
    for month in 0..11
      hash[month] = month
    end
    return hash
  end
  
  ## 日プルダウンを取得するためのMap
  def getDayMap
    hash = {}
    ## 1日～31日まで取得
    for day in 1..31
      hash[day] = day
    end
    return hash
  end

  ## 3項目(年月日や電話番号)から～番目を指定して取得する
  ## 例 getThree("1988-05-08", 'second') → "05"
  def getThree(value, number)
    ## 空は対象外
    if value.present?
      value = value.split("-")
      ## 分割(split)されなかった場合はnilを返す
      return nil if value.size <= 1
      ## numberが「first」の場合は1番目、「second」の場合は2番目、「third」の場合は3番目、それ以外はnilを返す
      return number == 'first' ? value[0] : number == 'second' ? value[1] : number == 'third' ? value[2] : nil
    end
  end

  ## 誕生日から実年齢を取得するメソッド
  def getAge(birthday)
    today = Date.today.to_time.strftime('%Y%m%d').to_i
    birth = birthday.to_time.strftime('%Y%m%d').to_i
    return ((today - birth)/10000).to_i
  end

  ## 経験年数から経験月数を取得するメソッド(例. 5年8ヶ月 → 68ヶ月)
  def getTotalMonth(year, month)
    return year * 12 + month
  end

  ## 経験月数から経験年数を取得し表示するメソッド(例. 85ヶ月 → 7年1ヶ月)
  def getYearAndMonth(totalMonth)
    year = totalMonth / 12
    month = totalMonth - year * 12
    return year == 0 ? month.to_s + "ヶ月" : year.to_s + "年" + month.to_s + "ヶ月"
  end

  ## 経験月数から経験年数を取得し配列形式で返すメソッド(例. 85ヶ月 → [7, 1])
  def getYearAndMonthArray(totalMonth)
    year = totalMonth / 12
    month = totalMonth - year * 12
    return year, month
  end

  ## スキルIDからスキル名を取得するメソッド
  def getSkillName(skill_id)
    return Skill.find_by(skill_id: skill_id).skill_name
  end

  ## 保持スキルがあるか否かのCSS(display,disabled)を返す
  def isPossessedSkills(possessedSkills)
    if possessedSkills.present?
      return "display:none;", nil
    else
      return nil, "disabled=disabled"
    end
  end

  ## 最も経歴の長いスキル(ID)を取得するメソッド(スキルある人だけ)
  def getMostExperientedSkillId(employee_number)
    possessedSkill = PossessedSkill.where(employee_number: employee_number)
    return possessedSkill.present? ? possessedSkill.map {|ps| [ps.skill_id, ps.month]}.max {|x,y| x[1]<=>y[1]}[0] : nil
  end

end

app/views/users/detail.html.erb
<% provide(:title, 'エンジニア詳細') %>

<script>

  $(document).ready(function(){

    // 「more」又は「close」リンクを押下した回数(デフォルトは0回)
    var count = 0;

    // 6行目以降は非表示
    $('ul:gt(5)').hide();

    // 保持スキルの高さ調整(プラスPadding10px分も)
    $('#thSkill').height($('td#tdSkill').height()+10);
    // お気に入り案件の高さ調整(プラスPadding10px分も)
    $('#thFavoriteProject').height($('td#tdFavoriteProject').height()+10);
    // スキルシートの高さ調整
    $('#thSkillSheet').height($('td#tdSkillSheet').height());

    // 未入力OK(備考)の高さ調整
    if(!$('#tdDescription').text().trim()) { // 備考
      $('#tdDescription').height($('#thDescription').height());
    }

    // 「アップロード」ボタンの初期表示は非活性
    $('#upload').attr('disabled', true);

    // スキルアイコンを触れると経験年数吹き出しが出る
    $("#tdSkill div").hover(
      function(){
        var width = $(this).width();
        $(this).width(width);
        var text = $(this).find('#month').val();
        $(this).append('<div class="tooltips">'+text+'</div>');
        // 吹き出しの幅は75px
        $('.tooltips').width(75);
      },
      function(){
        $(this).find(".tooltips").remove();
      }
    );

    // お気に入り案件枠の「more」or「close」リンクを押下した場合の処理
    $("#toggle").click(function(){
      if(count%2 == 0) {
        // 6行目以降表示し、リンク名を「close」に変更
        $('ul:gt(5)').show(); $(this).text("close");
        // さらに11行以上の場合はスクロールを表示、高さを調整する
        if($('div#favorite ul').length > 10) {
          $('div#favorite').css('overflow','auto'); $('div#favorite').css('height', '300px');
        }
      } else {
        // 6行目以降非表示し、リンク名を「more」に変更
        $('ul:gt(5)').hide(); $(this).text("more");
        // さらに11行以上の場合はスクロールを非表示、高さを調整する
        if($('div#favorite ul').length > 10) {
          $('div#favorite').css('overflow',''); $('div#favorite').css('height', '');
        }
      }
      // 上記に応じて高さを調整
      $('#thFavoriteProject').height($('td#tdFavoriteProject').height()+10);
      count++;
    });

    // ファイル(PDF or xls or xlsx形式)選択された場合に「アップロード」ボタンが活性化するメソッド
    $(document).on('change', '[name=skillSheet]', function() {
      if(!$.isEmptyObject($(this).val())) {
        $('#upload').attr('disabled', false);
      } else {
        // 「PDF or xls or xlsx」形式のファイル選択後に「キャンセル」ボタン押下した場合
        $('#upload').attr('disabled', true);
      }
    });

    // 「アップロード」ボタンを押下した場合の処理
    $(document).on('click', '#upload', function() {
      // 活性化のみ
      if(!$(this).attr('disabled')) {
        var formData = new FormData($('#uploadForm').get(0));
        var employeeNumber = location.pathname.split('/')[2]; // 「/users/社員番号/detail」の2番目を取得
        formData.append("id", employeeNumber);
        upload(formData);
      }
    });

    // 「アップロードし直す」ボタン押下処理
    $(document).on('click', '#reUpload', function() {
      // スキルシート枠のtdタグ書き換え
      $('#tdSkillSheet').html(
        '<form id="uploadForm">'
          + '<input type="file" id="skillSheet" name="skillSheet" accept=".xls,.xlsx,.pdf" style="height:30px; margin-bottom:0px;">'
          + '<div id="upload" class="btn btn-primary" style="margin-top:5px;">アップロード</div>'
        + '</form>'
      );
      // 「アップロード」ボタンは非活性
      $('#upload').attr('disabled', true);
      // スキルシートの高さ調整
      $('#thSkillSheet').height($('td#tdSkillSheet').height());
    });

    // ファイルオブジェクトをもとにファイルアップロード処理を呼び出すメソッド
    function upload(formData) {
      $.ajax({
        url : '/users/upload',
        type: 'POST',
        data: formData,
        processData: false,
        contentType: false,
        dataType: 'json'
      }).done(function(data){
        location.reload(); // アップロード成功しても失敗しても「エンジニア詳細」画面をリロード
        $('html,body').animate({ scrollTop: 0 }, '1'); // スクロールトップへ移動
      });
    }

  })

</script>

<h3>エンジニア詳細</h3>

<div style="margin-top:30px; margin-left:auto; margin-right:auto; display:table;">
  <table class="table-bordered table-condensed engineer-detail-left">
    <tbody>
      <tr>
        <th>社員番号</th>
      </tr>
      <tr>
        <th>氏名</th>
      </tr>
      <tr>
        <th>性別</th>
      </tr>
      <tr>
        <th>所属</th>
      </tr>
      <tr>
        <th>生年月日(年齢)</th>
      </tr>
      <tr>
        <th>電話番号</th>
      </tr>
      <tr>
        <th>最寄り駅</th>
      </tr>
      <% unless @user.admin_flag? %>
        <tr>
          <th>希望単価</th>
        </tr>
      <% end %>
      <tr>
        <th>就業形態</th>
      </tr>
      <% unless @user.admin_flag? %>
        <tr>
          <th>参画可能日</th>
        </tr>
        <% if @join.present? %>
          <tr>
            <th>参画終了予定日</th>
          </tr>
        <% end %>
        <tr>
          <th id="thSkill">保持スキル</th>
        </tr>
        <tr>
          <th id="thFavoriteProject">お気に入り案件</th>
        </tr>
        <tr>
          <th id="thSkillSheet">スキルシート</th>
        </tr>
      <% end %>
      <tr>
        <th id="thDescription">備考</th>
      </tr>
    </tbody>
  </table>

  <table class = "table-bordered table-condensed engineer-detail-right">
    <tbody>
      <tr>
        <td style="text-align:left;"><%= @user.employee_number %></td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= @user.name %></td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= {"male":"男性", "female":"女性"}[@user.gender.to_sym] %></td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= @user.department %></td>
      </tr>
      <tr>
        <td style="text-align:left;">
          <%= @user.birthday.to_date.strftime('%Y年%-m月%-d日') + "（"+ getAge(@user.birthday).to_s + "歳）"%>
        </td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= @user.telephone_number %></td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= @user.nearest_station %></td>
      </tr>
      <% unless @user.admin_flag? %>
        <tr>
          <td style="text-align:left;">
            <%= getPriceDisplay(@user.price_min) + "　～　" + getPriceDisplay(@user.price_max) %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td style="text-align:left;">
          <%= {"fullTime":"正社員", "contract":"契約社員", "subcontract":"業務委託"}[@user.working_style.to_sym] %>
        </td>
      </tr>
      <% unless @user.admin_flag? %>
        <tr>
          <td style="text-align:left;">
            <% unless @join.present? %>
              <% if @user.join_able_date.present? %>
                <%= @user.join_able_date.to_date.strftime('%Y年%-m月%-d日') + ' ～' %>
              <% else %>
                未定
              <% end %>
            <% else %>
            <%= link_to '案件参画中', project_detail_path(@join.project_id) %>
            <% end %>
          </td>
        </tr>
        <% if @join.present? %>
          <tr>
            <td style="text-align:left;">
              <%= endDate = @join.end_date; endDate.present? ? '～ ' + endDate.to_date.strftime('%Y年%-m月%-d日') : '未定' %>
            </td>
          </tr>
        <% end %>
        <tr>
          <% unless @possessedSkills.empty? %>
            <td id="tdSkill" style="text-align:left; padding:10px;">
              <% @possessedSkills.each do |possessedSkill| %>
                <div class="btn btn-primary btn-sm" style="cursor:default;">
                  <input type="hidden" name="month" id="month" value=<%= getYearAndMonth(possessedSkill.month) %>>
                  <%= getSkillName(possessedSkill.skill_id) %>
                </div>
              <% end %>
              <% if current_user.admin_flag? %>
                <br><p style="margin-top:10px; margin-bottom:0px;"><%= link_to 'マッチする案件照会', user_matching_path(@user.employee_number) %></p>
              <% end %>
            </td>
          <% else %>
            <td style="text-align:left;">なし</td>
          <% end %>
        </tr>
        <tr>
          <% unless @favoriteProjects.empty? %>
            <td id="tdFavoriteProject" style="text-align:left; padding:10px;">
              <div id="favorite" style="margin-top:10px; margin-bottom:10px;">
              <% @favoriteProjects.each_with_index do |favoriteProject, index| %>
                <ul>
                  <li>
                    <%= "「" + User.find(favoriteProject[1]).name + "」さんからおすすめ案件" %> : <%= link_to favoriteProject[0], project_detail_path(favoriteProject[0]) %>
                    <br>
                  </li>
                </ul>
              <% end %>
              </div>
              <% if @favoriteProjects.count > 5 %><a href="javascript:void(0)" id="toggle" style="float:right;">more</a><% end %>
            </td>
          <% else %>
            <td style="text-align:left;">なし</td>
          <% end %>
        </tr>
        <tr>
          <td id="tdSkillSheet" style="text-align:left;">
            <% if @skillSheetInfo.present? %>
              <%= link_to @skillSheetInfo.file_name, user_download_path(@user.employee_number), method: :post %>
              <br>
              <div id="reUpload" class="btn btn-primary" style="margin-top:5px;">アップロードし直す</div>
            <% else %>
              <form id="uploadForm">
                <input type="file" id="skillSheet" name="skillSheet" accept=".xls,.xlsx,.pdf" style="height:30px; margin-bottom:0px;">
                <div id="upload" class="btn btn-primary" style="margin-top:5px;">アップロード</div>
              </form>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td id="tdDescription" style="text-align:left;"><%= @user.description %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<% provide(:title, 'エンジニア一覧') %>

<script>

  // tableの行をhover
  $(function(){
    $("table tbody tr").hover(function() {
      $(this).css('background-color','#fafafa');
    }, function() {
      $(this).css('background-color','');
    });
  });

</script>

<div style="height:75px;">
  <h3>エンジニア一覧</h3>
  <%= link_to " ＋ エンジニア新規登録", users_new_path, class:"btn btn-primary", :style=>"float:left;" %>
  <%= link_to "エンジニア検索", users_search_path, class:"btn btn-primary", :style=>"float:right;" %>
</div>

<div style="display:flex; height:150px; align-items:center; text-align:right; justify-content:flex-end;">
  <p style="font-size:20px;">
    登録者数 : <%= @count.to_s + '名' %><br>
    空き要員数 :
    <% if @notJoinCount.present? %>
      <%= link_to @notJoinCount.count.to_s + '名', user_filter_path("notJoin") %>
    <% else %>
      0名
    <% end %>
    <br>
    当月終了予定数 :
    <% if @thisMonthEndNum.present? %>
      <%= link_to @thisMonthEndNum.count.to_s + '名', user_filter_path("thisMonth") %>
    <% else %>
      0名
    <% end %>
    <br>
    翌月終了予定数 :
    <% if @nextMonthEndNum.present? %>
      <%= link_to @nextMonthEndNum.count.to_s + '名', user_filter_path("nextMonth") %>
    <% else %>
      0名
    <% end %>
  </p>
</div>

<%= will_paginate :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<% if @users.present? %>
  <% if @users.count <= 25 %>
    <table class="table-bordered table-condensed" style="margin-top:50px;">
  <% else %>
    <table class="table-bordered table-condensed">
  <% end %>
    <thead>
      <tr style="background-color:#ebebeb;">
        <th>氏名</th>
        <th>所属</th>
        <th>年齢</th>
        <th>最寄駅</th>
        <th>主要スキル</th>
        <th style="width:200px;"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_detail_path(user) %></td>
          <td><%= user.department %></td>
          <td><%= getAge(user.birthday).to_s + "歳" %></td>
          <td><%= user.nearest_station %></td>
          <td>
            <% if getMostExperientedSkillId(user.employee_number) %>
              <div class="btn btn-primary" style="cursor:default;">
                <%= getSkillName(getMostExperientedSkillId(user.employee_number)) %>
              </div>
            <% else %>
              なし
            <% end %>
          </td>
          <td>
            <%= link_to "更新する", users_edit_path(user.employee_number), class: "btn btn-warning" %>
            <%= link_to "削除する", user_delete_path(user.employee_number), method: :delete,
              data: { confirm: user.name + "さんの情報を削除してよろしいですか？" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else%>
  <h1 style="margin-top:75px;">
    該当のエンジニアは存在しません。
  </h1>
<% end %>

<%= will_paginate :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

app/views/users/matching.html.erb
<% provide(:title, 'エンジニアマッチング') %>

<script>

  // tableの行をhover
  $(function(){
    $("table tbody tr").hover(function() {
      $(this).css('background-color','#fafafa');
    }, function() {
      $(this).css('background-color','');
    });
  });

  // お気に入りチェックボックス押下処理
  $(function(){
    $(document).on('change', '#favorite', function() {
      $.ajax({
        url: '/api/v1/users/favorite',
        type: 'POST',
        data: {
          project_id: $(this).closest('tr').find('#projectId').text(),
          employee_number: location.pathname.split('/')[2], // 「/users/社員番号/matching」の2番目を取得
          favorite: $(this).prop('checked')
        },
        dataType: 'json'
      }).done(function(data){
      });
    });
  });

</script>

<div>
  <h3>「<%= User.find(params[:id]).name %>」さんの案件マッチング</h3>
</div>

<%= will_paginate @skillMatchInfos, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<table id="userMatching" class="table-bordered table-condensed">
  <thead>
    <tr style="background-color:#ebebeb;">
      <th>案件番号</th>
      <th>案件名</th>
      <th>案件開始日</th>
      <th>マッチングスキル</th>
      <th>この案件にお気に入り</th>
    </tr>
  </thead>
  <tbody>
    <% @skillMatchInfos.each do |skillMatchInfo| %>
      <tr style="height:50px;">
        <% @project = Project.find(skillMatchInfo[0]) %>
        <td id="projectId"><%= link_to skillMatchInfo[0], project_detail_path(skillMatchInfo[0]) %></td>
        <td id="name"><%= @project.project_name %></td>
        <td id="startDate"><%= Date.parse(@project.start_date).strftime("%Y年%-m月%-d日　～") %></td>
        <td id="matchingSkills">
          <% skillMatchInfo[1][1].each do |matchingSkillId| %>
            <div class="btn btn-primary btn-sm" style="margin-right:10px; cursor:default;">
              <%= getSkillName(matchingSkillId) %>
            </div>
          <% end %>
        </td>
        <td style="width:15%;">
          <input type="checkbox" id="favorite" <%= @favoriteProjects.include?(skillMatchInfo[0]) ? "checked" : "" %>>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @skillMatchInfos, :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>