config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#top'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    'users' , to: 'users#index', as: 'users'
  get    'users/filter/:id', to: 'users#index', as: 'user_filter'
  delete 'users/:id' , to: 'users#destroy', as: 'user_delete'
  get    'users/new' , to: 'users#new'
  post   'users/new' , to: 'users#new', as: 'user_new'
  get    'users/:id/edit' , to: 'users#edit', as: 'users_edit'
  post   'users/edit' , to: 'users#edit', as: 'user_edit'
  get    'users/confirm' , to: 'users#confirm'
  post   'users/confirm' , to: 'users#confirm', as: 'user_confirm'
  get    'users/:id/detail' , to: 'users#detail', as: 'user_detail'
  get    'users/search' , to: 'users#search'
  post   'users/search',  to: 'users#search', as: 'user_search'
  get    'users/:id/matching' , to: 'users#matching', as: 'user_matching'
  post   'users/upload' , to: 'users#upload'
  post   'users/:id/download' , to: 'users#download', as: 'user_download'
  get    'projects' , to: 'projects#index', as: 'projects'
  get    'projects/new' , to: 'projects#new'
  post   'projects/new' , to: 'projects#new', as: 'project_new'
  get    'projects/:id/edit' , to: 'projects#edit', as: 'projects_edit'
  post   'projects/edit' , to: 'projects#edit', as: 'project_edit'
  get    'projects/confirm' , to: 'projects#confirm'
  post   'projects/confirm' , to: 'projects#confirm', as: 'project_confirm'
  get    'projects/:id/detail' , to: 'projects#detail', as: 'project_detail'
  get    'projects/search' , to: 'projects#search'
  post   'projects/search',  to: 'projects#search', as: 'project_search'
  get    'projects/:id/matching' , to: 'projects#matching', as: 'project_matching'
  namespace 'api' do
    namespace 'v1' do
      post   'users/search',  to: 'users#search', as: 'user_search'
      get    'users/favorite',  to: 'users#favorite'
      post   'users/favorite',  to: 'users#favorite', as: 'user_favorite'
      post   'projects/search',  to: 'projects#search', as: 'project_search'
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < ApplicationController

      ## SQL結合文字列(長いのでここで定義)
      @@joinQuery = "LEFT OUTER JOIN project_members m ON projects.project_id = m.project_id
                      LEFT OUTER JOIN project_must_skills ms ON projects.project_id = ms.project_id
                        LEFT OUTER JOIN project_want_skills ws ON projects.project_id = ws.project_id"
      ## 参画有無(定数)
      JOIN_OR_NOT = ["無", "有"]

      def search
        ## 検索結果
        result = []
        ## 条件配列
        jouken = ["","",""]
        ## 単価
        if params[:price].present?
          ## 「〇〇円 ～ 〇〇円」を選択した場合
          if params[:price].include?("BETWEEN")
            min = params[:price]["BETWEEN".length+1..params[:price].index("AND")-2]
            max = params[:price][params[:price].index("AND")+"AND".length+1..]
            jouken[0] = sprintf(" AND ((price_min IS NOT NULL AND price_max IS NOT NULL AND (price_min %s OR price_max %s))
                                    OR (price_min IS NULL AND price_max IS NOT NULL AND price_max >= %d)
                                      OR (price_min IS NOT NULL AND price_max IS NULL AND price_min <= %d))",
                                        params[:price], params[:price], max, min)
          else
            value = params[:price][params[:price].index(" ")+1..]
          end
          ## 「～ 〇〇円」を選択した場合
          if params[:price].include?("<=")
            jouken[0] = " AND ((price_min IS NOT NULL AND price_min <= #{value}) OR (price_max IS NOT NULL AND price_max >= #{value}))"
          ## 「〇〇円 ～」を選択した場合
          elsif params[:price].include?(">=")
            jouken[0] = " AND ((price_min IS NOT NULL AND price_min >= #{value}) OR (price_max IS NOT NULL AND price_max >= #{value}))"
          end
        end
        ## スキル
        if params[:skills]
          ## スキル以外に他に入力されている場合
          if params[:price].present? or params[:engineer].present?
            params[:skills].each do |skill|
              jouken[1]  = jouken[1] + " AND (must_skill_id = " + skill + " OR want_skill_id = " + skill + ")"
            end
          ## スキルのみ入力されている場合
          else
            ## 選択したスキルが1つの場合
            if params[:skills].count == 1
              jouken[1] = " AND must_skill_id = ? OR want_skill_id = ?"
            elsif params[:skills].count >= 2
              jouken[1] = " AND must_skill_id IN (?) OR want_skill_id IN (?)"
            end
          end
        end
        ## 参画有無
        if params[:joinOrNot]
          ## 参画無
          if params[:joinOrNot] == JOIN_OR_NOT[0]
            joinsJouken = "m.start_date is null AND m.end_date is null"
          ## 参画有
          elsif params[:joinOrNot] == JOIN_OR_NOT[1]
            now = Date.today.strftime("%Y-%m-%d")
            joinsJouken = "(m.start_date is not null AND m.end_date is null) OR (#{now} <= m.end_date)"
          end
        end
        ## 参画エンジニア
        if params[:engineer].present?
          jouken[2] = " AND m.employee_number = " + params[:engineer]
        end
        result = Project.joins(@@joinQuery)
                  .where("1 = 1" + jouken[0] + jouken[1] + jouken[2], params[:skills], params[:skills])
                    .where("working_place like ?", "%"+params[:work_place]+"%")
                      .where(joinsJouken)
                        .order(project_id: "DESC").distinct
        render json: result.count
      end

    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  ## 単価を金額表示(3桁区切り)にするメソッド
  def getPriceDisplay(price)
    return price.present? ? price.to_s(:delimited).concat("円") : ""
  end

  ## スキルIDからスキル名を取得するメソッド
  def getSkillName(skill_id)
    return Skill.find_by(skill_id: skill_id).skill_name
  end

  ## 社員番号からユーザー情報を取得するメソッド
  def getUser(employee_number)
    return User.find(employee_number)
  end

  ## 金額の幅を表示するメソッド
  def getPriceDsp
    price = {}
    ## 一旦400000円～1000000円
    for i in 4..10
      if i == 4
        price["<= "+(i*100000).to_s] = "～ "+(i*100000).to_s(:delimited).concat("円")
      elsif i == 10
        price["BETWEEN "+((i-1)*100000).to_s+" AND "+(i*100000).to_s] = ((i-1)*100000).to_s(:delimited).concat("円 ～ ")+(i*100000).to_s(:delimited).concat("円")
        price[">= "+(i*100000).to_s] = (i*100000).to_s(:delimited).concat("円 ～")
      else
        price["BETWEEN "+((i-1)*100000).to_s+" AND "+(i*100000).to_s] = ((i-1)*100000).to_s(:delimited).concat("円 ～ ")+(i*100000).to_s(:delimited).concat("円")
      end
    end
    return price
  end

  ## 月プルダウンを取得するためのMap
  def getMonthMap
    hash = {}
    ## 1月～12月まで取得
    for month in 1..12
      hash[month] = month
    end
    return hash
  end

  ## 日プルダウンを取得するためのMap
  def getDayMap
    hash = {}
    ## 1日～31日まで取得
    for day in 1..31
      hash[day] = day
    end
    return hash
  end

  ## 時(hour)プルダウンを取得するためのMap
  def getHourMap
    hash = {}
    ## 0時～23時まで取得
    for hour in 0..23
      hash[hour] = hour
    end
    return hash
  end

  ## 分(minutes)プルダウンを取得するためのMap
  def getMinutesMap
    hash = {}
    ## 0分～59分まで15分刻みで取得
    for minutes in 0..59
      if minutes % 15 == 0
        hash[minutes] = format("%02d", minutes)
      end
    end
    return hash
  end

  ## 2項目(時間)から～番目を指定して取得する
  ## 例 getTwo("05:08", 'second') → "08"
  def getTwo(value, number)
    ## 空は対象外
    if value.present?
      value = value.split(":")
      ## 分割(split)されなかった場合はnilを返す
      return nil if value.size <= 1
      ## numberが「first」の場合は1番目、「second」の場合は2番目、それ以外はnilを返す
      return number == 'first' ? value[0].to_i : number == 'second' ? value[1].to_i : nil
    end
  end

  ## 3項目(年月日や電話番号)から～番目を指定して取得する
  ## 例 getThree("1988-05-08", 'second') → "05"
  def getThree(value, number)
    ## 空は対象外
    if value.present?
      value = value.split("-")
      ## 分割(split)されなかった場合はnilを返す
      return nil if value.size <= 1
      ## numberが「first」の場合は1番目、「second」の場合は2番目、「third」の場合は3番目、それ以外はnilを返す
      return number == 'first' ? value[0] : number == 'second' ? value[1] : number == 'third' ? value[2] : nil
    end
  end

end

app/views/projects/detail.html.erb
<% provide(:title, '案件詳細') %>

<script>

  $(document).ready(function(){

    // 未入力OK(環境、募集人数、備考 etc)の高さ調整
    if(!$('#tdEnvironment').text().trim()) { // 環境
      $('#tdEnvironment').height($('#thEnvironment').height());
    }
    if(!$('#tdApplicantNum').text().trim()) { // 募集人数
      $('#tdApplicantNum').height($('#thApplicantNum').height());
    }
    if(!$('#tdDescription').text().trim()) { // 備考
      $('#tdDescription').height($('#thDescription').height());
    }

    // スキルの高さ調整
    $('#thMustSkill').height($('#tdMustSkill').height());
    $('#thWantSkill').height($('#tdWantSkill').height());

    // 参画メンバーの高さ調整
    $('#thjoinMember').height($('#tdJoinMember').height());

  });

</script>

<h3>案件詳細</h3>

<div style="margin-top:30px; margin-left:auto; margin-right:auto; display:table;">
  <table class="table-bordered table-condensed project-detail-left">
    <tbody>
      <tr>
        <th>案件番号</th>
      </tr>
      <tr>
        <th>案件名</th>
      </tr>
      <tr>
        <th>案件概要</th>
      </tr>
      <tr>
        <th>作業場所</th>
      </tr>
      <tr>
        <th>単金</th>
      </tr>
      <tr>
        <th>精算</th>
      </tr>
      <tr>
        <th>案件開始日</th>
      </tr>
      <tr>
        <% if @project.end_date.present? %>
          <th>案件終了予定日</th>
        <% else %>
          <th>案件終了日</th>
        <% end %>
      </tr>
      <tr>
        <th>稼働時間</th>
      </tr>
      <tr>
        <th id="thEnvironment">環境</th>
      </tr>
      <tr>
        <th id="thMustSkill">必須スキル</th>
      </tr>
      <tr>
        <th id="thWantSkill">尚可スキル</th>
      </tr>
      <tr>
        <th id="thjoinMember">参画メンバー</th>
      </tr>
      <tr>
        <th id="thApplicantNum">募集人数</th>
      </tr>
      <tr>
        <th id="thDescription">備考</th>
      </tr>
    </tbody>
  </table>

  <table class = "table-bordered table-condensed project-detail-right">
    <tbody>
      <tr>
        <td style="text-align:left;"><%= @project.project_id %></td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= @project.project_name %></td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= @project.content %></td>
      </tr>
      <tr>
        <td style="text-align:left;"><%= @project.working_place %></td>
      </tr>
      <tr>
        <td style="text-align:left;">
          <%= getPriceDisplay(@project.price_min) + "　～　" + getPriceDisplay(@project.price_max) %>
        </td>
      </tr>
      <tr>
        <td style="text-align:left;">
          <%= @project.min.to_s + "H　～　" + @project.max.to_s + "H" %>
        </td>
      </tr>
      <tr>
        <td style="text-align:left;">
          <%= @project.start_date.to_date.strftime('%Y年%-m月%-d日') + "　～" %>
        </td>
      </tr>
      <tr>
        <td style="text-align:left;">
          <% if @project.end_date.present? %>
            <%= "～　" + @project.end_date.to_date.strftime('%Y年%-m月%-d日') %>
          <% else %>
            未定
          <% end %>
        </td>
      </tr>
      <tr>
        <td style="text-align:left;">
          <% if @project.start_time.present? and @project.end_time.present? %>
            <%= @project.start_time + "　～　" + @project.end_time %>
          <% else %>
            未公開
          <% end %>
        </td>
      </tr>
      <tr>
        <td id="tdEnvironment" style="text-align:left;"><%= @project.environment %></td>
      </tr>
      <tr>
        <td id="tdMustSkill" style="text-align:left;">
          <% @projectSkills.each_with_index do |projectSkill, index| %>
            <% if (index == 0 and @projectSkills.count == 1) or @projectSkills.count == index+1 %>
              <div class="btn btn-primary btn-sm" style="cursor:default;">
                <%= getSkillName(projectSkill.must_skill_id) %>
              </div>
            <% else %>
              <div class="btn btn-primary btn-sm" style="margin-right:10px; cursor:default;">
                <%= getSkillName(projectSkill.must_skill_id) %>
              </div>
            <% end %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td id="tdWantSkill" style="text-align:left;">
          <% if @projectWantSkills.present? %>
            <% @projectWantSkills.each_with_index do |projectWantSkill, index| %>
              <% if (index == 0 and @projectWantSkills.count == 1) or @projectWantSkills.count == index+1 %>
                <div class="btn btn-primary btn-sm" style="cursor:default;">
                  <%= getSkillName(projectWantSkill.want_skill_id) %>
                </div>
              <% else %>
                <div class="btn btn-primary btn-sm" style="margin-right:10px; cursor:default;">
                  <%= getSkillName(projectWantSkill.want_skill_id) %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            特になし
          <% end %>
        </td>
      </tr>
      <tr>
        <td id="tdJoinMember" style="text-align:left;">
          <% if @projectMembers.present? %>
            <% if current_user.admin_flag %>
              <% @projectMembers.each_with_index do |projectMember, index| %>
                <%= link_to getUser(projectMember.employee_number).name, user_detail_path(projectMember.employee_number) %>
                <% cnt = @projectMembers.count; if cnt > 1 and index+1 < cnt %>
                  <br>
                <% end %>
              <% end %>
            <% else %>
              <%= @projectMembers.count.to_s + "名参画中" %>
            <% end %>
          <% else %>
            なし
          <% end %>
        </td>
      </tr>
      <tr>
        <td id="tdApplicantNum" style="text-align:left;">
          <%= num = @project.applicant_num; nil != (num =~ /\A[0-9]+\z/) ? num + "名" : num %>
        </td>
      </tr>
      <tr>
        <td id="tdDescription" style="text-align:left;"><%= @project.description %></td>
      </tr>
    </tbody>
  </table>

</div>

<% if current_user.admin_flag? %>
  <div style="margin-top:25px; text-align:center;">
    <%= link_to "マッチング", project_matching_path(@project.project_id), class: "btn btn-warning", :style=>"width:25%;" %>
    <%= link_to "案件情報を更新", projects_edit_path(@project.project_id), class: "btn btn-warning", :style=>"width:25%;" %>
  </div>
<% end %>

app/views/projects/index.html.erb
<% provide(:title, '案件一覧') %>

<div style="height:75px;">
  <h3>案件一覧</h3>
  <% if current_user.admin_flag %>
    <%= link_to " ＋ 案件新規登録", projects_new_path, class:"btn btn-primary", :style=>"float:left;" %>
  <% end %>
  <%= link_to "案件検索", projects_search_path, class:"btn btn-primary", :style=>"float:right;" %>
</div>

<div style="display:flex; height:50px; align-items:center; text-align:right; justify-content:flex-end;">
  <p style="font-size:20px;">
    登録案件数 : <%= @count.to_s + '件' %>
  </p>
</div>

<%= will_paginate :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<% if @projects.present? %>
  <% @projects.each_with_index do |project, index| %>
    <% if index % 10 == 0 and @projects.count > 10 %>
      <table id="project" class="table-bordered table-condensed"
        style="width:90%; margin-left:auto; margin-right:auto; border-top:none; border-left:none; border-right:none;">
    <% else %>
      <table id="project" class="table-bordered table-condensed"
        style="margin-top:30px; width:90%; margin-left:auto; margin-right:auto; border-top:none; border-left:none; border-right:none;">
    <% end %>
      <thead>
        <tr>
          <td id="projectName" colspan="4">
            <%= link_to project.project_name, project_detail_path(project.project_id) %>
          </td>
        </tr>
        <tr>
          <th>内容</th>
          <td colspan="3"><%= project.content %></td>
        </tr>
        <tr>
          <th>単価</th>
          <td id="price">
            <%= getPriceDisplay(project.price_min) + "　～　" + getPriceDisplay(project.price_max) %>
          </td>
          <th>作業場所</th>
          <td><%= project.working_place %></td>
        </tr>
        <tr>
          <th>必須スキル</th>
          <td colspan="3">
            <% @projectSkills.where("project_id = ?", project.project_id).each_with_index do |projectSkill, index| %>
              <% if (index == 0 and @projectSkills.where("project_id = ?", project.project_id).count == 1) or @projectSkills.where("project_id = ?", project.project_id).count == index+1 %>
                <div class="btn btn-primary" style="cursor:default;">
                  <%= getSkillName(projectSkill.must_skill_id) %>
                </div>
              <% else %>
                <div class="btn btn-primary" style="margin-right:10px; cursor:default;">
                  <%= getSkillName(projectSkill.must_skill_id) %>
                </div>
              <% end %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>備考</th>
          <td colspan="3"><%= project.description %></td>
        </tr>
      </thead>
    </table>
  <% end %>
<% else%>
  <h1 style="margin-top:50px;">
    該当の案件は存在しません。
  </h1>
<% end %>

<%= will_paginate :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

app/views/projects/matching.html.erb
<% provide(:title, '案件マッチング') %>

<script>

  // プルダウン表示
  var pulldown = ['上位10ユーザー表示', '空きメンバーに絞る', '参画可能タイミングが合致メンバに絞る'];

  // 起動時
  $(document).ready(
    function(){
      // プルダウン生成は1度だけ
      if(!($('#dispCondition option').length == pulldown.length)) addPulldownData($('#dispCondition'));
    }
  );

  // tableの行をhover
  $(function(){
    $("table tbody tr").hover(function() {
      $(this).css('background-color','#fafafa');
    }, function() {
      $(this).css('background-color','');
    });
  });

  // 表示方法プルダウン
  $(function(){
    $('#dispCondition').change(function(){
      if($(this).val() == pulldown[0]) {
        displayCss('#top10', '');
        displayCss('#notJoin, #joinableTiming', 'none');
      } else if($(this).val() == pulldown[1]) {
        displayCss('#notJoin', '');
        displayCss('#top10, #joinableTiming', 'none');
      } else if($(this).val() == pulldown[2]) {
        displayCss('#joinableTiming', '');
        displayCss('#top10, #notJoin', 'none');
      }
    });
  });

  // プログレスバーを触れるとマッチング率吹き出しが出る
  $(document).ready(
    function(){
      $('progress#rate').hover(function(e) {
        var text = $(this).val() + ' ％';
        $(this).parent().append('<div class="tooltips">'+text+'</div>');
        // 吹き出しの幅・高さ・位置などを設定
        $('.tooltips').css({
          width:"75px", height:"30px", left:e.pageX, top:e.pageY
        });
      }, function() {
        $('.tooltips').remove();
      });
    }
  );

  // プルダウンの選択項目を作成するメソッド
  function addPulldownData(element) {
    for(let i = 0 ; i < pulldown.length ; i++) {
      var option = document.createElement("option");
      option.selected = (i == 0) ? true : false;
      option.innerText = pulldown[i];
      element.append(option);
    }
  }

  // displayプロパティ共通メソッド
  function displayCss(element, disp) {
    for(let i = 0 ; i < $(element).length ; i++) {
      $(element).css('display', disp);
    }
  }

</script>

<div>
  <h3 style="word-break:break-all;">案件「<%= Project.find(params[:id]).project_name %>」の案件マッチング</h3>
</div>
<div>
  <h3 style="margin-bottom:0px;">
    案件開始日 : <%= Date.parse(Project.find(params[:id]).start_date).strftime("%Y年%-m月%-d日") %>
    <select class="form-control" id="dispCondition" style="float:right;"></select>
  </h3>
</div>

<table class="table-bordered table-condensed" style="margin-top:50px;">
  <thead>
    <tr style="background-color:#ebebeb;">
      <th>氏名</th>
      <th>所属</th>
      <th>最寄り駅</th>
      <th style="width:150px;">参画可能日</th>
      <th>参画中</th>
      <th>マッチング率</th>
    </tr>
  </thead>
  <tbody id="top10">
    <% @matching.keys.each_with_index do |m, index| %>
      <tr style="height:50px;">
        <td><%= link_to getUser(m).name, user_detail_path(m) %></td>
        <td><%= getUser(m).department %></td>
        <td><%= getUser(m).nearest_station %></td>
        <td>
          <%= join = getUser(m).join_able_date; join.present? ? Date.parse(join).strftime("%Y年%-m月%-d日〜") : "未定" %>
        </td>
        <td>
          <% if ProjectMember.where("project_id = ? AND employee_number = ? AND end_date is null", params[:id], m).present? %>
            この案件に参画中
          <% elsif ProjectMember.where("project_id <> ? AND employee_number = ? AND (end_date is null OR #{Date.today.strftime("%Y-%m-%d")} <= end_date)", params[:id], m).present? %>
            <%= link_to '別の案件に参画中', project_detail_path(ProjectMember.where("project_id <> ? AND employee_number = ? AND (end_date is null OR #{Date.today.strftime("%Y-%m-%d")} <= end_date)", params[:id], m).maximum(:project_id)) %>
          <% else %>
            未参画
          <% end %>
        </td>
        <td id="matchingRate">
          <progress max="100" id="rate" value="<%= @matching[m] %>" style="vertical-align: middle;"></progress>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tbody id="notJoin" style="display:none;">
    <% @matchingNotJoin.keys.each_with_index do |m, index| %>
      <tr style="height:50px;">
        <td><%= link_to getUser(m).name, user_detail_path(m) %></td>
        <td><%= getUser(m).department %></td>
        <td><%= getUser(m).nearest_station %></td>
        <td>
          <%= join = getUser(m).join_able_date; join.present? ? Date.parse(join).strftime("%Y年%-m月%-d日〜") : "未定" %>
        </td>
        <td>
          <% if ProjectMember.where("project_id = ? AND employee_number = ? AND end_date is null", params[:id], m).present? %>
            この案件に参画中
          <% elsif ProjectMember.where("project_id <> ? AND employee_number = ? AND (end_date is null OR #{Date.today.strftime("%Y-%m-%d")} <= end_date)", params[:id], m).present? %>
            <%= link_to '別の案件に参画中', project_detail_path(ProjectMember.where("project_id <> ? AND employee_number = ? AND (end_date is null OR #{Date.today.strftime("%Y-%m-%d")} <= end_date)", params[:id], m).maximum(:project_id)) %>
          <% else %>
            未参画
          <% end %>
        </td>
        <td id="matchingRate">
          <progress max="100" id="rate" value="<%= @matchingNotJoin[m] %>" style="vertical-align: middle;"></progress>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tbody id="joinableTiming" style="display:none;">
    <% @matchingJoinableTiming.keys.each_with_index do |m, index| %>
      <tr style="height:50px;">
        <td><%= link_to getUser(m).name, user_detail_path(m) %></td>
        <td><%= getUser(m).department %></td>
        <td><%= getUser(m).nearest_station %></td>
        <td>
          <%= join = getUser(m).join_able_date; join.present? ? Date.parse(join).strftime("%Y年%-m月%-d日〜") : "未定" %>
        </td>
        <td>
          <% if ProjectMember.where("project_id = ? AND employee_number = ? AND end_date is null", params[:id], m).present? %>
            この案件に参画中
          <% elsif ProjectMember.where("project_id <> ? AND employee_number = ? AND (end_date is null OR #{Date.today.strftime("%Y-%m-%d")} <= end_date)", params[:id], m).present? %>
            <%= link_to '別の案件に参画中', project_detail_path(ProjectMember.where("project_id <> ? AND employee_number = ? AND (end_date is null OR #{Date.today.strftime("%Y-%m-%d")} <= end_date)", params[:id], m).maximum(:project_id)) %>
          <% else %>
            未参画
          <% end %>
        </td>
        <td id="matchingRate">
          <progress max="100" id="rate" value="<%= @matchingJoinableTiming[m] %>" style="vertical-align: middle;"></progress>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>