config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#top'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    'users' , to: 'users#index', as: 'users'
  get    'users/filter/:id', to: 'users#index', as: 'user_filter'
  delete 'users/:id' , to: 'users#destroy', as: 'user_delete'
  get    'users/new' , to: 'users#new'
  post   'users/new' , to: 'users#new', as: 'user_new'
  get    'users/:id/edit' , to: 'users#edit', as: 'users_edit'
  post   'users/edit' , to: 'users#edit', as: 'user_edit'
  get    'users/confirm' , to: 'users#confirm'
  post   'users/confirm' , to: 'users#confirm', as: 'user_confirm'
  get    'users/:id/detail' , to: 'users#detail', as: 'user_detail'
  get    'users/search' , to: 'users#search'
  post   'users/search',  to: 'users#search', as: 'user_search'
  get    'users/:id/matching' , to: 'users#matching', as: 'user_matching'
  post   'users/upload' , to: 'users#upload'
  post   'users/:id/download' , to: 'users#download', as: 'user_download'
  get    'projects' , to: 'projects#index', as: 'projects'
  get    'projects/new' , to: 'projects#new'
  post   'projects/new' , to: 'projects#new', as: 'project_new'
  get    'projects/:id/edit' , to: 'projects#edit', as: 'projects_edit'
  post   'projects/edit' , to: 'projects#edit', as: 'project_edit'
  get    'projects/confirm' , to: 'projects#confirm'
  post   'projects/confirm' , to: 'projects#confirm', as: 'project_confirm'
  get    'projects/:id/detail' , to: 'projects#detail', as: 'project_detail'
  get    'projects/search' , to: 'projects#search'
  post   'projects/search',  to: 'projects#search', as: 'project_search'
  get    'projects/:id/matching' , to: 'projects#matching', as: 'project_matching'
  namespace 'api' do
    namespace 'v1' do
      post   'users/search',  to: 'users#search', as: 'user_search'
      get    'users/favorite',  to: 'users#favorite'
      post   'users/favorite',  to: 'users#favorite', as: 'user_favorite'
      post   'projects/search',  to: 'projects#search', as: 'project_search'
    end
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-info">
  <div class="container" style="width:auto;">
    <% if logged_in? %>
      <%= link_to "社内案件マッチング", current_user.admin_flag? ? users_path : user_detail_path(current_user), id: "logo" %>
    <% else %>
      <p id="logo">社内案件マッチング</p>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <% if current_user.admin_flag? %>
            <li>
              <%= link_to "Employee", users_path %>
            </li>
            <li>
              <%= link_to "Project", projects_path %>
            </li>
            <li>
              <%= link_to "Profile", user_detail_path(current_user) %>
            </li>
          <% else %>
            <li>
              <%= link_to "Project", projects_path %>
            </li>
            <li>
              <%= link_to "Profile", user_detail_path(current_user) %>
            </li>
            <li>
              <%= link_to "Edit", users_edit_path(current_user) %>
            </li>
          <% end %>
          <li>
            <%= link_to "Logout", logout_path, method: :delete, class:"btn btn-primary" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="margin">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>